### ISSUE TITLE
[enhancement] - ability to hold and delete an app

### ISSUE THREAD

**Issue by premnirmal** [nicholasrout/lens-launcher#12]
Right now the only way to delete an app (using lens launcher) would be to go into Settings -> Apps -> and delete the app you want to. It would be nice to be able to delete the app straight from the grid

**Comment by nicholasrout** [comment]
Hi @premnirmal,

Do you have any UX suggestions for how this would work?

**Comment by premnirmal** [comment]
Hi @nicholasrout 
How about the way google now launcher does it? Press and hold on an app icon, then drag it to the top to delete

**Comment by premnirmal** [comment]
closing this, because you can delete an app from the lens launcher apps tab

**Comment by wesinator** [comment]
I think this is still a good idea. see also #39
