### ISSUE TITLE
[enhancement] Allow launch by shortcut

### ISSUE THREAD

**Issue by benplumley** [nicholasrout/lens-launcher#14]
If a shortcut to the launcher view of lens-launcher was added to the system-wide shortcuts list, it could be used as the app drawer view for an arbitrary launcher. For example:

arbitrary launcher settings -> drawer settings -> use custom drawer -> shortcut -> lens-launcher-shortcut

**Comment by nicholasrout** [comment]
Hi @benplumley - thanks for the suggestion, I will be releasing this in an update in the next few days 👍

**Comment by nicholasrout** [comment]
Release in 2.3.0
