### ISSUE TITLE
Change .gitignore file

### ISSUE THREAD

**Issue by CreaRo** [nicholasrout/lens-launcher#2]
I've been trying to merge new changes but the .idea/ (and some other auto generated files) are killing it for me! The following .gitignore would remove the unneeded files which are currently being tracked by git.

Replace the current .gitignore with this.
https://gist.github.com/vtanathip/9414323

As far as I know, you might need to remove the currently unneeded tracked files once from your repo and from then onwards git won't track them.

**Comment by nicholasrout** [comment]
Hi @CreaRo,

Apologies, have been meaning to do this for a while! Done now.
