### ISSUE TITLE
Is there any config require to run this source code?

### ISSUE THREAD

**Issue by JVeverGiveUp** [nicholasrout/lens-launcher#26]
Dear devs,
I import project to Android Studio, no issue but when I run. Force close occur immediately. Here are the log:
FATAL EXCEPTION: main  Process: nickrout.lenslauncher, PID: 10440 android.database.sqlite.SQLiteException: no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1
Error Code : 1 (SQLITE_ERROR)Caused By : SQL(query) error or missing database. (no such table: APP_PERSISTENT (code 1): , while compiling: SELECT * FROM APP_PERSISTENT WHERE (M_IDENTIFIER = ? ) LIMIT 1)
...
at nickrout.lenslauncher.model.AppPersistent.getAppVisibility(AppPersistent.java:129)
 at nickrout.lenslauncher.adapter.AppRecyclerAdapter$AppViewHolder.setAppElement(AppRecyclerAdapter.java:108)
at nickrout.lenslauncher.adapter.AppRecyclerAdapter.onBindViewHolder(AppRecyclerAdapter.java:74)

**Comment by CreaRo** [comment]
This is because of SugarORM - a database lib we've used. Try to do the following:

- Disable instant run
- Update the meta-data tag in manifest and increment the version as in the following `<meta-data android:name="VERSION" android:value="2" />`

**Comment by JVeverGiveUp** [comment]
Disable Instant run is okay to me. I doesn't need to update meta-data version. Thanks for your support!
